name: ISO Evidence CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  iso-evidence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Generate KPI snapshot
        run: |
          python scripts/update_kpis.py

      - name: Run ISO/MCP tests only
        run: |
          pytest -q tests/test_mcp_validation.py


