[global]
developmentMode = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#6fffb0"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1f2b"
textColor = "#ffffff"

[client]
showErrorDetails = false 