[theme]
base = "dark"
primaryColor = "#6fffb0"
backgroundColor = "#0f1116"
secondaryBackgroundColor = "#1a1f2b"
textColor = "#e5e7eb"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false 