[server]
# Streamlit Cloud Configuration
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1f2b"
textColor = "#ffffff"

[global]
developmentMode = false
showErrorDetails = false

# Force requirements-streamlit.txt usage
[deployment]
requirementsFile = "requirements-streamlit.txt" 