[server]
port = 8501
enableCORS = true
enableXsrfProtection = true
enableStaticServing = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#6fffb0"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1f2b"
textColor = "#ffffff" 